Added community feed support to community wall
BuildFire/communityWall pull request #47
Opened 2021-09-27 17:16 UTC by alikaakati

2021-09-28 17:32 UTC, NenoR96 approved these changes

2021-11-01 14:03 UTC, nteske approved these changes

2021-11-05 16:18 UTC, nteske requested changes

2021-11-05 16:18 UTC, nteske commented on widget/controllers/widget.members.controller.js
> +                console.log("here");
Please remove console logs

2021-11-05 16:23 UTC, nteske approved these changes

2021-11-11 17:49 UTC, merged